global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 1.0
   publish_frequency: 0.5
   transform_tolerance: 1.0

  # 靜態地圖（不滾動）
   static_map: true
   rolling_window: false
   resolution: 0.05
   track_unknown_space: true
   map_type: costmap

   plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}  # 啟用
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

    # - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}

GlobalPlanner:
  allow_unknown: true  # 從 false 改為 true
  default_tolerance: 0.5